# -*- coding: utf-8 -*-
"""semana_01_e2.ipynb

Automatically generated by Colab.

Original file is located at

## Ejercicio 1: Verificación de Número Positivo/Negativo

### Objetivo:
Determinar si un número ingresado es positivo o negativo.
### Código con errores:
"""

numero = input("Ingrese un número: ")
if numero > 0:
    print("El número es positivo.")
else:
    print("El número es negativo.")

"""### Pistas:
- input() devuelve una cadena de texto, no un número.
-  Las comparaciones numéricas requieren que la variable numero sea un entero.
-  La condición del else cubre solo negativos, ¿qué pasa si el numero es cero?.

####################################################################################################

## Ejercicio 2: Verificación de Múltiplo de 3

### Objetivo:
Determinar si un número es múltiplo de 3.

### Código con errores:
"""

numero = input("Ingrese un número: ")
if numero % 3 = 0:
    print("Es múltiplo de 3.")
else:
    print("No es múltiplo de 3.")

"""### Pistas:
- El operador de asignación no es el correcto para comparar.
- el valor ingresado por input es string.
- Recuerda usar el operador módulo (`%`) para obtener el resto de una división.

####################################################################################################

## Ejercicio 3: Determinación de la Letra Inicial

### Objetivo:
Verificar si una palabra inicia con la letra 'a'.

### Código con errores:
"""

palabra = input("Ingrese una palabra: ")
if palabra[0] = "a":
    print("La palabra inicia con 'a'.")
else:
    print("La palabra no inicia con 'a'.")

"""### Pistas:
- Los string tiene posiciones igual que un array.
- El operador de asignación no es el correcto para comparar.
- recuerda usar ".lower()" en caso que el usuario ingrese "A".

####################################################################################################

## Ejercicio 4: Categorización por Rango de Edad

### Objetivo: Asignar una categoría de edad (niño, adolescente, adulto) según la edad ingresada.

### Código con errores:
"""

edad = input("Ingrese su edad: ")
if edad < 12:
    print("Niño.")
if edad >= 12 and edad < 18:
    print("Adolescente.")
else:
    print("Adulto.")

"""### Pistas:
- Recuerde convertir el valor de entrada a entero.
- El primer "if" debe ser un "elif" para evitar que se ejecuten multiples bloques if.
- Recuerda que tienes que verificar los rangos de edad.

####################################################################################################

## Ejercicio 5: Verificación de Condiciones Múltiples

## Objetivo: Verificar si un número es positivo y par o si es negativo e impar.

## Código con errores:
"""

numero = input("Ingrese un número: ")
if numero > 0 and numero % 2 = 0:
    print("Positivo y par.")
elif numero < 0 and numero % 2 = 1:
    print("Negativo e impar.")
else:
    print("Otra condición.")

"""## Pistas:
- input siempre retorna string.
- verifica los operadores de comparación.
- comprueba si el valor es positivo o negativo.

####################################################################################################
"""